In [67]:
import numpy as np
import matplotlib.pyplot as plt
import csv
import os

folder1 = 'D:/Research/Attenuation Data/CSV Files/'
folder2 = 'D:/Research/Attenuation Data/NPY Files/'

dirs = os.listdir(folder1)

for file in dirs:
    
    with open(folder1+file, 'rt') as csvfile:
        spamreader = csv.reader(csvfile, delimiter=',')
            
        matrix = []
        for csv_row in spamreader:
            matrix.append(csv_row)
        matrix = np.array(matrix)

        file = file.replace('.csv', '.npy')
        np.save(folder2+file, matrix)
        print(file)
        

Z01.npy
Z02.npy
Z03.npy
Z04.npy
Z05.npy
Z06.npy
Z07.npy
Z08.npy
Z09.npy
Z10.npy
Z11.npy
Z12.npy
Z13.npy
Z14.npy
Z15.npy
Z16.npy
Z17.npy
Z18.npy
Z19.npy
Z20.npy
Z21.npy
Z22.npy
Z23.npy
Z24.npy
Z25.npy
Z26.npy
Z27.npy
Z28.npy
Z29.npy
Z30.npy


In [68]:
atomic_mass = np.array([1.00797, 4.0026, 6.941, 9.01218, 10.81, 12.011, 14.0067, 15.9994, 18.998403, 20.179, 
                              22.98977, 24.305, 26.98154, 28.0855, 30.97376, 32.06, 35.453, 39.948, 39.0983, 40.08, 
                              44.9559, 47.90, 50.9415, 51.996, 54.9380, 55.847, 58.9332, 58.70, 63.546, 65.38])

NA = 6.022E23
#density = np.array([0.0899E-3, 0.1785E-3, 0.534, 1.848, 2.34, 2.26, 1.2506E-3, 1.429E-3, 1.696E-3, 0.9E-3, 0.971, 1.738, 
 #                   2.702, 2.33, 1.82, 2.07, 3.214E-3, 1.7824E-3, 0.862, 1.55, 2.99, 4.54, 6.11, 7.19, 7.43, 7.874, 8.9, 
  #                  8.9, 8.96, 7.13])

atomic_number = np.arange(1, 31)

correction_factor = np.divide(atomic_mass, NA)


files = os.listdir(folder2)   
i = 0
for file in files:
    data = np.load(folder2+file)
    data = np.array(data, dtype='float')
    print(file)
    print(correction_factor[i])
    data[:, 1] = np.divide(data[:, 1], atomic_number[i])
    data[:, 1] = np.multiply(data[:, 1], atomic_mass[i])
    data[:, 2] = np.multiply(data[:, 2], atomic_mass[i])
    data[:, 2] = np.divide(data[:, 2], atomic_number[i]**5)
    i += 1
    np.save(folder2+file, data)
    #print(file)
        

Z01.npy
1.6738126868150116e-24
Z02.npy
6.646629026901362e-24
Z03.npy
1.152607107273331e-23
Z04.npy
1.4965426768515445e-23
Z05.npy
1.7950846894719363e-23
Z06.npy
1.994520092992361e-23
Z07.npy
2.325921620724012e-23
Z08.npy
2.6568249750913313e-23
Z09.npy
3.1548327798073725e-23
Z10.npy
3.350880106276984e-23
Z11.npy
3.8176303553636663e-23
Z12.npy
4.036034540019927e-23
Z13.npy
4.4804948522085683e-23
Z14.npy
4.6638160079707735e-23
Z15.npy
5.1434340750581196e-23
Z16.npy
5.323812686815012e-23
Z17.npy
5.887246761873132e-23
Z18.npy
6.633676519428761e-23
Z19.npy
6.492577216871472e-23
Z20.npy
6.655596147459315e-23
Z21.npy
7.465277316506144e-23
Z22.npy
7.954168050481567e-23
Z23.npy
8.45923281301893e-23
Z24.npy
8.634340750581203e-23
Z25.npy
9.122882763201595e-23
Z26.npy
9.273829292593823e-23
Z27.npy
9.786316838259714e-23
Z28.npy
9.747592162072402e-23
Z29.npy
1.0552308203254732e-22
Z30.npy
1.0856858186648953e-22


In [69]:
print(np.load(folder2+file))

[[1.00000000e-03 1.14427640e+01 4.16494815e-03]
 [1.01000000e-03 1.14320918e+01 4.07077942e-03]
 [1.02000000e-03 1.14214218e+01 3.97930123e-03]
 [1.02000000e-03 1.14214218e+01 9.47337366e-03]
 [1.03100000e-03 1.14086073e+01 1.28634477e-02]
 [1.04300000e-03 1.13979787e+01 1.74561909e-02]
 [1.04300000e-03 1.13979787e+01 2.21511745e-02]
 [1.11600000e-03 1.13168465e+01 2.09538864e-02]
 [1.19400000e-03 1.12271299e+01 1.98238617e-02]
 [1.19400000e-03 1.12271299e+01 2.25762790e-02]
 [1.50000000e-03 1.08681610e+01 1.29656881e-02]
 [2.00000000e-03 1.02297907e+01 6.37656790e-03]
 [3.00000000e-03 8.95788815e+00 2.22507243e-03]
 [4.00000000e-03 7.78725925e+00 1.03047490e-03]
 [5.00000000e-03 6.75057217e+00 5.61514650e-04]
 [6.00000000e-03 5.85416879e+00 3.40083621e-04]
 [8.00000000e-03 4.47146896e+00 1.52499523e-04]
 [9.65900000e-03 3.65988523e+00 8.98100576e-05]
 [9.65900000e-03 3.65988523e+00 6.77745761e-04]
 [1.00000000e-02 3.52646644e+00 6.22589794e-04]
 [1.50000000e-02 2.24364546e+00 2.156194